import {
  lstat,
  mkdir,
  readFile,
  realpath,
  readdir,
  rename,
  rm,
  stat,
  symlink,
  writeFile,
} from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  artifactRevisionFile,
  contentRevision,
  rewriteArtifactLinks,
} from './artifact-html.mjs';
import { renderMarkdownArtifact } from './markdown.mjs';
import { writeSearchIndex } from './search-index.mjs';
import { acquireSyncLock, describeLockOwner, isProcessAlive } from './watcher-lock.mjs';

const scriptsDirectory = path.dirname(fileURLToPath(import.meta.url));
export const docShelfRoot = path.resolve(scriptsDirectory, '..');
const workspaceRoot = path.resolve(docShelfRoot, '..');
export const defaultManifestPath = path.join(docShelfRoot, 'artifacts.json');
export const localManifestPath = path.join(docShelfRoot, 'artifacts.local.json');
export const generatedArtifactsRoot = path.join(docShelfRoot, 'public', 'artifacts');
export const generatedManifestPath = path.join(docShelfRoot, 'src', 'generated', 'artifacts.json');
export const runtimeRoot = path.join(docShelfRoot, '.docshelf-runtime');
const artifactRootPrefix = 'artifacts-';
const artifactOutputMarker = '.docshelf-artifact-output';
const artifactOutputMarkerContents = 'Generated by DocShelf.\n';
const legacyMarkdownRootPrefix = 'markdown-';
const legacyMarkdownOutputMarker = '.docshelf-markdown-output';

/**
 * @typedef {object} Artifact
 * @property {string} project
 * @property {string} source
 * @property {string} route
 * @property {string} title
 * @property {string} description
 * @property {string} sourcePath
 * @property {'html' | 'markdown'} format
 */

/**
 * @typedef {object} ArtifactManifest
 * @property {1} version
 * @property {Artifact[]} artifacts
 */

/** @returns {Promise<ArtifactManifest>} */
export async function loadArtifactManifest() {
  const localManifestStats = await stat(localManifestPath).catch(() => null);
  const manifestPath = localManifestStats ? localManifestPath : defaultManifestPath;
  return loadArtifactManifestFrom(manifestPath);
}

/** @param {string} manifestPath @returns {Promise<ArtifactManifest>} */
export async function loadArtifactManifestFrom(manifestPath) {
  const contents = await readFile(manifestPath, 'utf8');
  /** @type {unknown} */
  let parsed;

  try {
    parsed = JSON.parse(contents);
  } catch (error) {
    throw new Error(`Could not parse ${manifestPath}`, { cause: error });
  }

  if (!isRecord(parsed) || parsed.version !== 1 || !Array.isArray(parsed.artifacts)) {
    throw new Error(`${path.basename(manifestPath)} must contain version 1 and an artifacts array.`);
  }

  const routes = new Set();
  const sources = new Set();
  /** @type {Artifact[]} */
  const artifacts = [];

  for (const [index, entry] of parsed.artifacts.entries()) {
    if (!isRecord(entry)) {
      throw new Error(`Artifact ${index + 1} must be an object.`);
    }

    const project = requiredString(entry, 'project', index);
    const source = requiredString(entry, 'source', index);
    const route = requiredString(entry, 'route', index);
    const title = requiredString(entry, 'title', index);
    const description = requiredString(entry, 'description', index);

    validateSource(source, index);
    validateRoute(route, index);

    if (routes.has(route)) {
      throw new Error(`Artifact ${index + 1} duplicates route ${route}.`);
    }

    const sourcePath = path.resolve(docShelfRoot, source);
    const resolvedSource = await realpath(sourcePath).catch(() => null);

    if (!resolvedSource) {
      throw new Error(`Artifact ${index + 1} source does not exist: ${source}`);
    }

    const sourceStats = await stat(resolvedSource);
    if (!sourceStats.isFile()) {
      throw new Error(`Artifact ${index + 1} source is not a file: ${source}`);
    }

    if (!isWithin(workspaceRoot, resolvedSource)) {
      throw new Error(
        `Artifact ${index + 1} source is outside the workspace root (the parent directory of DocShelf): ${source}`,
      );
    }

    if (sources.has(resolvedSource)) {
      throw new Error(`Artifact ${index + 1} duplicates source ${source}.`);
    }

    routes.add(route);
    sources.add(resolvedSource);
    artifacts.push({
      project,
      source,
      route,
      title,
      description,
      sourcePath: resolvedSource,
      format: sourceFormat(source),
    });
  }

  return { version: 1, artifacts };
}

/** @param {Artifact} artifact */
export function artifactUrl(artifact) {
  return `/artifacts/${artifact.route}`;
}

/**
 * Regenerate public/artifacts and the generated manifest from the registered sources.
 *
 * Every caller serializes on the artifact-sync lock: `npm run sync` and the `pre*` hooks wait for
 * a rebuilding watcher instead of replacing the symlink tree underneath its Astro build. The
 * watcher passes `lock: false` because it holds the lock for its whole rebuild.
 *
 * @param {ArtifactManifest} manifest
 * @param {{ lock?: boolean }} [options]
 */
export async function syncArtifacts(manifest, options = {}) {
  if (options.lock === false) return replaceGeneratedArtifacts(manifest);

  const syncLock = await acquireSyncLock(runtimeRoot, {
    onWait: (owner) => {
      console.error(`Waiting for ${describeLockOwner(owner)} to release the artifact sync lock.`);
    },
  });
  try {
    return await replaceGeneratedArtifacts(manifest);
  } finally {
    syncLock.release();
  }
}

/** @param {ArtifactManifest} manifest */
async function replaceGeneratedArtifacts(manifest) {
  const publicRoot = path.join(docShelfRoot, 'public');
  const stagingRoot = path.join(publicRoot, `.artifacts-${process.pid}.tmp`);
  const artifactBuildName = `${artifactRootPrefix}${Date.now()}-${process.pid}`;
  const artifactBuildRoot = path.join(runtimeRoot, artifactBuildName);
  const artifactStagingRoot = path.join(runtimeRoot, `.staging-${artifactBuildName}`);
  let published = false;

  await rm(stagingRoot, { recursive: true, force: true });
  await rm(artifactStagingRoot, { recursive: true, force: true });
  await rm(artifactBuildRoot, { recursive: true, force: true });
  await mkdir(stagingRoot, { recursive: true });

  try {
    await mkdir(artifactStagingRoot, { recursive: true });
    await writeFile(
      path.join(artifactStagingRoot, artifactOutputMarker),
      artifactOutputMarkerContents,
    );
    const stagedMarker = await readFile(
      path.join(artifactStagingRoot, artifactOutputMarker),
      'utf8',
    );
    if (stagedMarker !== artifactOutputMarkerContents) {
      throw new Error(`Could not validate generated artifact output: ${artifactStagingRoot}`);
    }
    await rename(artifactStagingRoot, artifactBuildRoot);

    const sourceSnapshots = await readArtifactSources(manifest);
    const revisionEntries = [];

    for (const artifact of manifest.artifacts) {
      const destination = path.join(stagingRoot, ...artifact.route.split('/'));
      await mkdir(path.dirname(destination), { recursive: true });
      const snapshot = sourceSnapshots.get(artifact.sourcePath);
      if (!snapshot) throw new Error(`Missing source snapshot for ${artifact.route}.`);

      let html;
      if (artifact.format === 'markdown') {
        html = await renderMarkdownArtifact(artifact, snapshot.contents.toString('utf8'));
      } else {
        html = snapshot.contents.toString('utf8');
      }

      html = await rewriteArtifactLinks(html, artifact, manifest);
      html = markArtifactForSearch(html, artifact.route);
      const outputPath = path.join(artifactBuildRoot, ...artifact.route.split('/'));
      await mkdir(path.dirname(outputPath), { recursive: true });
      await writeFile(outputPath, html);

      revisionEntries.push({
        route: artifact.route,
        revision: contentRevision(html),
        sourceRevision: snapshot.revision,
      });

      const target = path.relative(path.dirname(destination), outputPath);
      await symlink(target, destination, 'file');
    }

    const revisionState = createRevisionState(manifest, revisionEntries);
    const revisionStatePath = path.join(artifactBuildRoot, artifactRevisionFile);
    await writeFile(revisionStatePath, `${JSON.stringify(revisionState, null, 2)}\n`);
    await symlink(
      path.relative(stagingRoot, revisionStatePath),
      path.join(stagingRoot, artifactRevisionFile),
      'file',
    );

    await assertSymlinkTree(generatedArtifactsRoot);
    const staleArtifactRoots = await findGeneratedArtifactRoots(artifactBuildRoot);
    await writeGeneratedManifest(manifest, revisionState);
    await rm(generatedArtifactsRoot, { recursive: true, force: true });
    await rename(stagingRoot, generatedArtifactsRoot);
    published = true;

    for (const staleRoot of staleArtifactRoots) {
      await rm(staleRoot, { recursive: true, force: true });
    }

    return revisionState;
  } finally {
    await rm(stagingRoot, { recursive: true, force: true });
    await rm(artifactStagingRoot, { recursive: true, force: true });
    if (!published) await rm(artifactBuildRoot, { recursive: true, force: true });
  }
}

/** @param {ArtifactManifest} manifest @param {ArtifactRevisionState} revisionState */
async function writeGeneratedManifest(manifest, revisionState) {
  const revisions = new Map(
    revisionState.artifacts.map((artifact) => [artifact.route, artifact.revision]),
  );
  const generatedManifest = {
    version: manifest.version,
    catalogRevision: revisionState.catalogRevision,
    artifacts: manifest.artifacts.map(({ project, route, title, description }) => ({
      project,
      route,
      title,
      description,
      revision: revisions.get(route),
    })),
  };

  await mkdir(path.dirname(generatedManifestPath), { recursive: true });
  await writeFile(generatedManifestPath, `${JSON.stringify(generatedManifest, null, 2)}\n`);
}

/**
 * Validate the synchronized artifact revisions and ensure Pagefind's content
 * marker remains present without changing source artifacts owned by other projects.
 *
 * @param {ArtifactManifest} manifest
 */
export function artifactBuildIntegration(manifest) {
  return {
    name: 'docshelf-artifacts',
    hooks: {
      'astro:build:done': async ({ dir }) => {
        const outputRoot = fileURLToPath(dir);
        const revisionState = JSON.parse(
          await readFile(
            path.join(outputRoot, 'artifacts', artifactRevisionFile),
            'utf8',
          ),
        );
        await assertArtifactSourcesUnchanged(manifest, revisionState);
        const revisions = new Map(
          revisionState.artifacts.map((artifact) => [artifact.route, artifact.revision]),
        );

        for (const artifact of manifest.artifacts) {
          const outputPath = path.join(outputRoot, 'artifacts', ...artifact.route.split('/'));
          const html = await readFile(outputPath, 'utf8');
          if (contentRevision(html) !== revisions.get(artifact.route)) {
            throw new Error(
              `Built artifact does not match its synchronized revision: ${artifact.route}`,
            );
          }

          const searchableHtml = markArtifactForSearch(html, artifact.route);
          if (searchableHtml === html) continue;
          await writeFile(outputPath, searchableHtml);
        }
      },
    },
  };
}

/**
 * Confirm that the published snapshot still matches every registered source.
 *
 * @param {ArtifactManifest} manifest
 * @param {ArtifactRevisionState} revisionState
 */
export async function artifactSourcesMatch(manifest, revisionState) {
  const expected = new Map(
    revisionState.artifacts.map((artifact) => [artifact.route, artifact.sourceRevision]),
  );

  for (const artifact of manifest.artifacts) {
    const contents = await readFile(artifact.sourcePath).catch(() => null);
    if (!contents || contentRevision(contents) !== expected.get(artifact.route)) return false;
  }

  return true;
}

/**
 * @param {ArtifactManifest} manifest
 * @param {ArtifactRevisionState} revisionState
 */
async function assertArtifactSourcesUnchanged(manifest, revisionState) {
  if (!(await artifactSourcesMatch(manifest, revisionState))) {
    throw new Error(
      'A registered artifact changed during the build; rebuild from a fresh snapshot.',
    );
  }
}

/** @param {string} html @param {string} route */
function markArtifactForSearch(html, route) {
  if (html.includes('data-pagefind-body')) return html;
  if (!/<body(?:\s|>)/i.test(html)) {
    throw new Error(`Cannot mark artifact for search because it has no body: ${route}`);
  }
  return html.replace(/<body(?=\s|>)/i, '<body data-pagefind-body');
}

export function artifactSearchIntegration() {
  return {
    name: 'docshelf-artifact-search',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        const pageCount = await writeSearchIndex(fileURLToPath(dir));
        logger.info(`Built one search index for ${pageCount} HTML files.`);
      },
    },
  };
}

/** @param {string} root */
async function assertSymlinkTree(root) {
  const rootStats = await lstat(root).catch(() => null);
  if (!rootStats) return;
  if (!rootStats.isDirectory() || rootStats.isSymbolicLink()) {
    throw new Error(`${root} must be a generated directory.`);
  }

  const entries = await readdir(root, { withFileTypes: true });
  for (const entry of entries) {
    const entryPath = path.join(root, entry.name);

    if (entry.isDirectory()) {
      await assertSymlinkTree(entryPath);
      continue;
    }

    if (!entry.isSymbolicLink()) {
      throw new Error(
        `Refusing to replace non-symlink content in ${generatedArtifactsRoot}: ${entryPath}`,
      );
    }
  }
}

/** @param {string} activeRoot */
async function findGeneratedArtifactRoots(activeRoot) {
  const entries = await readdir(runtimeRoot, { withFileTypes: true });
  const staleRoots = [];

  for (const entry of entries) {
    const isCurrentOutput = entry.name.startsWith(artifactRootPrefix);
    const isLegacyMarkdownOutput = entry.name.startsWith(legacyMarkdownRootPrefix);
    if (!isCurrentOutput && !isLegacyMarkdownOutput) continue;

    const entryPath = path.join(runtimeRoot, entry.name);
    if (entryPath === activeRoot) continue;
    // Leave roots that another live DocShelf process may still be building from.
    const ownerPid = generatedRootPid(entry.name);
    if (ownerPid !== null && ownerPid !== process.pid && isProcessAlive(ownerPid)) continue;
    if (!entry.isDirectory() || entry.isSymbolicLink()) {
      throw new Error(`Refusing to remove unexpected artifact output: ${entryPath}`);
    }

    const markerName = isCurrentOutput ? artifactOutputMarker : legacyMarkdownOutputMarker;
    const marker = await readFile(path.join(entryPath, markerName), 'utf8').catch(() => null);
    if (marker !== artifactOutputMarkerContents) {
      throw new Error(`Refusing to remove unmarked artifact output: ${entryPath}`);
    }

    staleRoots.push(entryPath);
  }

  return staleRoots;
}

/** Generated roots are named `<prefix><timestamp>-<pid>`. @param {string} name */
function generatedRootPid(name) {
  const match = /-(\d+)$/.exec(name);
  return match ? Number(match[1]) : null;
}

/**
 * @typedef {object} ArtifactRevision
 * @property {string} route
 * @property {string} revision
 * @property {string} sourceRevision
 */

/**
 * @typedef {object} ArtifactRevisionState
 * @property {1} version
 * @property {string} revision
 * @property {string} catalogRevision
 * @property {ArtifactRevision[]} artifacts
 */

/** @param {ArtifactManifest} manifest */
async function readArtifactSources(manifest) {
  const snapshots = new Map();

  for (const artifact of manifest.artifacts) {
    const contents = await readFile(artifact.sourcePath);
    snapshots.set(artifact.sourcePath, {
      contents,
      revision: contentRevision(contents),
    });
  }

  return snapshots;
}

/** @param {ArtifactManifest} manifest @param {ArtifactRevision[]} artifacts */
function createRevisionState(manifest, artifacts) {
  return {
    version: 1,
    revision: contentRevision(
      JSON.stringify(artifacts.map(({ route, revision }) => ({ route, revision }))),
    ),
    catalogRevision: contentRevision(
      JSON.stringify(
        manifest.artifacts.map(({ project, route, title, description }) => ({
          project,
          route,
          title,
          description,
        })),
      ),
    ),
    artifacts,
  };
}

/** @param {unknown} value */
function isRecord(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * @param {Record<string, unknown>} entry
 * @param {string} key
 * @param {number} index
 */
function requiredString(entry, key, index) {
  const value = entry[key];
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`Artifact ${index + 1} requires a non-empty ${key}.`);
  }
  return value;
}

/** @param {string} source @param {number} index */
export function validateSource(source, index) {
  if (path.isAbsolute(source)) {
    throw new Error(`Artifact ${index + 1} source must be relative to DocShelf.`);
  }
  if (!['.html', '.md'].includes(path.extname(source).toLowerCase())) {
    throw new Error(`Artifact ${index + 1} source must be an HTML or Markdown file.`);
  }
}

/** @param {string} source @returns {'html' | 'markdown'} */
function sourceFormat(source) {
  return path.extname(source).toLowerCase() === '.md' ? 'markdown' : 'html';
}

/** @param {string} route @param {number} index */
export function validateRoute(route, index) {
  if (route.startsWith('/') || route.includes('\\')) {
    throw new Error(`Artifact ${index + 1} route must be relative and use forward slashes.`);
  }

  const segments = route.split('/');
  if (
    segments.some((segment) => !/^[a-z0-9][a-z0-9._-]*$/.test(segment)) ||
    path.posix.normalize(route) !== route ||
    !route.endsWith('.html')
  ) {
    throw new Error(`Artifact ${index + 1} has an invalid route: ${route}`);
  }
}

/** @param {string} root @param {string} candidate */
function isWithin(root, candidate) {
  const relativePath = path.relative(root, candidate);
  return relativePath !== '' && !relativePath.startsWith(`..${path.sep}`) && relativePath !== '..';
}
