import {
  lstat,
  mkdir,
  readFile,
  realpath,
  readdir,
  rename,
  rm,
  stat,
  symlink,
  writeFile,
} from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  artifactViewerUrl,
  artifactRevisionFile,
  contentRevision,
  rewriteArtifactLinks,
} from './artifact-html.mjs';
import { parseClaudeArtifactUrl } from '../src/lib/claude-artifacts.js';
import { renderMarkdownArtifact } from './markdown.mjs';
import { writeSearchIndex } from './search-index.mjs';
import { normalizeBasePath } from './site-path.mjs';
import { acquireSyncLock, describeLockOwner, isProcessAlive } from './watcher-lock.mjs';

const scriptsDirectory = path.dirname(fileURLToPath(import.meta.url));
export const docShelfRoot = path.resolve(scriptsDirectory, '..');
const workspaceRoot = path.resolve(docShelfRoot, '..');
export const defaultShelfPath = path.join(docShelfRoot, 'shelf.json');
export const localShelfPath = path.join(docShelfRoot, 'shelf.local.json');
export const legacyLocalShelfPath = path.join(docShelfRoot, 'artifacts.local.json');
export const generatedArtifactsRoot = path.join(docShelfRoot, 'public', 'artifacts');
export const generatedShelfPath = path.join(docShelfRoot, 'src', 'generated', 'shelf.json');
export const runtimeRoot = path.join(docShelfRoot, '.docshelf-runtime');
export const docshelfBasePath = normalizeBasePath(process.env.DOCSHELF_BASE);
const artifactRootPrefix = 'artifacts-';
const artifactOutputMarker = '.docshelf-artifact-output';
const artifactOutputMarkerContents = 'Generated by DocShelf.\n';
const legacyMarkdownRootPrefix = 'markdown-';
const legacyMarkdownOutputMarker = '.docshelf-markdown-output';

/**
 * @typedef {object} Artifact
 * @property {string} project
 * @property {string} source
 * @property {string} route
 * @property {string} title
 * @property {string} description
 * @property {string} [sourcePath]
 * @property {'html' | 'markdown' | 'claude'} format
 * @property {string} [embedUrl]
 */

/**
 * @typedef {object} Shelf
 * @property {1} version
 * @property {Artifact[]} artifacts
 */

/**
 * @param {{
 *   localPath?: string,
 *   legacyPath?: string,
 *   fallbackPath?: string,
 *   warn?: (message: string) => void,
 * }} [options]
 * @returns {Promise<Shelf>}
 */
export async function loadShelf(options = {}) {
  const shelfPath = await resolveShelfPath(options);
  return loadShelfFrom(shelfPath);
}

/**
 * Prefer the current local shelf name, but keep existing installations usable
 * while artifacts.local.json is migrated manually.
 *
 * @param {{
 *   localPath?: string,
 *   legacyPath?: string,
 *   fallbackPath?: string,
 *   warn?: (message: string) => void,
 * }} [options]
 */
export async function resolveShelfPath(options = {}) {
  const preferredPath = options.localPath || localShelfPath;
  const deprecatedPath = options.legacyPath || legacyLocalShelfPath;
  const fallbackPath = options.fallbackPath || defaultShelfPath;
  const warn = options.warn || console.warn;

  if (await stat(preferredPath).catch(() => null)) return preferredPath;
  if (await stat(deprecatedPath).catch(() => null)) {
    const deprecatedName = path.basename(deprecatedPath);
    const preferredName = path.basename(preferredPath);
    warn(
      `DocShelf is loading deprecated ${deprecatedName}. Rename it with: mv ${deprecatedName} ${preferredName}`,
    );
    return deprecatedPath;
  }
  return fallbackPath;
}

/** @param {string} shelfPath @returns {Promise<Shelf>} */
export async function loadShelfFrom(shelfPath) {
  const contents = await readFile(shelfPath, 'utf8');
  /** @type {unknown} */
  let parsed;

  try {
    parsed = JSON.parse(contents);
  } catch (error) {
    throw new Error(`Could not parse ${shelfPath}`, { cause: error });
  }

  if (!isRecord(parsed) || parsed.version !== 1 || !Array.isArray(parsed.artifacts)) {
    throw new Error(`${path.basename(shelfPath)} must contain version 1 and an artifacts array.`);
  }

  const routes = new Set();
  const sources = new Set();
  /** @type {Artifact[]} */
  const artifacts = [];

  for (const [index, entry] of parsed.artifacts.entries()) {
    if (!isRecord(entry)) {
      throw new Error(`Artifact ${index + 1} must be an object.`);
    }

    const project = requiredString(entry, 'project', index);
    const source = requiredString(entry, 'source', index);
    const route = requiredString(entry, 'route', index);
    const title = requiredString(entry, 'title', index);
    const description = requiredString(entry, 'description', index);

    validateRoute(route, index);

    if (routes.has(route)) {
      throw new Error(`Artifact ${index + 1} duplicates route ${route}.`);
    }

    const claudeArtifact = parseClaudeArtifactSource(source);
    if (claudeArtifact) {
      if (sources.has(claudeArtifact.publicUrl)) {
        throw new Error(`Artifact ${index + 1} duplicates source ${claudeArtifact.publicUrl}.`);
      }

      routes.add(route);
      sources.add(claudeArtifact.publicUrl);
      artifacts.push({
        project,
        source: claudeArtifact.publicUrl,
        route,
        title,
        description,
        format: 'claude',
        embedUrl: claudeArtifact.embedUrl,
      });
      continue;
    }

    if (/^[a-z][a-z\d+.-]*:/i.test(source) || source.startsWith('//')) {
      throw new Error(
        `Artifact ${index + 1} source URL must be a public Claude Artifact link.`,
      );
    }

    validateSource(source, index);

    const sourcePath = path.resolve(docShelfRoot, source);
    const resolvedSource = await realpath(sourcePath).catch(() => null);

    if (!resolvedSource) {
      throw new Error(`Artifact ${index + 1} source does not exist: ${source}`);
    }

    const sourceStats = await stat(resolvedSource);
    if (!sourceStats.isFile()) {
      throw new Error(`Artifact ${index + 1} source is not a file: ${source}`);
    }

    if (!isWithin(workspaceRoot, resolvedSource)) {
      throw new Error(
        `Artifact ${index + 1} source is outside the workspace root (the parent directory of DocShelf): ${source}`,
      );
    }

    if (sources.has(resolvedSource)) {
      throw new Error(`Artifact ${index + 1} duplicates source ${source}.`);
    }

    routes.add(route);
    sources.add(resolvedSource);
    artifacts.push({
      project,
      source,
      route,
      title,
      description,
      sourcePath: resolvedSource,
      format: sourceFormat(source),
    });
  }

  return { version: 1, artifacts };
}

/** @param {Artifact} artifact */
export function artifactUrl(artifact) {
  // Starlight's file-format formatter leaves this viewer link intact because
  // its query ends in the validated .html route. Preserve that suffix.
  if (artifact.format === 'claude') return artifactViewerUrl(artifact.route);
  // Starlight applies Astro's configured base path to sidebar links.
  return `/artifacts/${artifact.route}`;
}

/** @param {{ source: string, format?: string, title?: string }} artifact */
export function artifactFileName(artifact) {
  if (artifact.format === 'claude') return artifact.title || 'Claude Artifact';
  return path.basename(artifact.source);
}

/**
 * Regenerate public/artifacts and the generated shelf from the registered sources.
 *
 * Every caller serializes on the artifact-sync lock: `npm run sync` and the `pre*` hooks wait for
 * a rebuilding watcher instead of replacing the symlink tree underneath its Astro build. The
 * watcher passes `lock: false` because it holds the lock for its whole rebuild.
 *
 * @param {Shelf} shelf
 * @param {{ lock?: boolean }} [options]
 */
export async function syncArtifacts(shelf, options = {}) {
  if (options.lock === false) return replaceGeneratedArtifacts(shelf);

  const syncLock = await acquireSyncLock(runtimeRoot, {
    onWait: (owner) => {
      console.error(`Waiting for ${describeLockOwner(owner)} to release the artifact sync lock.`);
    },
  });
  try {
    return await replaceGeneratedArtifacts(shelf);
  } finally {
    syncLock.release();
  }
}

/** @param {Shelf} shelf */
async function replaceGeneratedArtifacts(shelf) {
  const publicRoot = path.join(docShelfRoot, 'public');
  const stagingRoot = path.join(publicRoot, `.artifacts-${process.pid}.tmp`);
  const artifactBuildName = `${artifactRootPrefix}${Date.now()}-${process.pid}`;
  const artifactBuildRoot = path.join(runtimeRoot, artifactBuildName);
  const artifactStagingRoot = path.join(runtimeRoot, `.staging-${artifactBuildName}`);
  let published = false;

  await rm(stagingRoot, { recursive: true, force: true });
  await rm(artifactStagingRoot, { recursive: true, force: true });
  await rm(artifactBuildRoot, { recursive: true, force: true });
  await mkdir(stagingRoot, { recursive: true });

  try {
    await mkdir(artifactStagingRoot, { recursive: true });
    await writeFile(
      path.join(artifactStagingRoot, artifactOutputMarker),
      artifactOutputMarkerContents,
    );
    const stagedMarker = await readFile(
      path.join(artifactStagingRoot, artifactOutputMarker),
      'utf8',
    );
    if (stagedMarker !== artifactOutputMarkerContents) {
      throw new Error(`Could not validate generated artifact output: ${artifactStagingRoot}`);
    }
    await rename(artifactStagingRoot, artifactBuildRoot);

    const sourceSnapshots = await readArtifactSources(shelf);
    const revisionEntries = [];

    for (const artifact of shelf.artifacts) {
      if (artifact.format === 'claude') {
        const revision = contentRevision(artifact.embedUrl || artifact.source);
        revisionEntries.push({
          route: artifact.route,
          revision,
          sourceRevision: revision,
        });
        continue;
      }

      const destination = path.join(stagingRoot, ...artifact.route.split('/'));
      await mkdir(path.dirname(destination), { recursive: true });
      const snapshot = sourceSnapshots.get(artifact.sourcePath);
      if (!snapshot) throw new Error(`Missing source snapshot for ${artifact.route}.`);

      let html;
      if (artifact.format === 'markdown') {
        html = await renderMarkdownArtifact(artifact, snapshot.contents.toString('utf8'), {
          basePath: docshelfBasePath,
        });
      } else {
        html = snapshot.contents.toString('utf8');
      }

      html = await rewriteArtifactLinks(html, artifact, shelf, {
        basePath: docshelfBasePath,
      });
      html = markArtifactForSearch(html, artifact.route);
      const outputPath = path.join(artifactBuildRoot, ...artifact.route.split('/'));
      await mkdir(path.dirname(outputPath), { recursive: true });
      await writeFile(outputPath, html);

      revisionEntries.push({
        route: artifact.route,
        revision: contentRevision(html),
        sourceRevision: snapshot.revision,
      });

      const target = path.relative(path.dirname(destination), outputPath);
      await symlink(target, destination, 'file');
    }

    const revisionState = createRevisionState(shelf, revisionEntries);
    const revisionStatePath = path.join(artifactBuildRoot, artifactRevisionFile);
    await writeFile(revisionStatePath, `${JSON.stringify(revisionState, null, 2)}\n`);
    await symlink(
      path.relative(stagingRoot, revisionStatePath),
      path.join(stagingRoot, artifactRevisionFile),
      'file',
    );

    await assertSymlinkTree(generatedArtifactsRoot);
    const staleArtifactRoots = await findGeneratedArtifactRoots(artifactBuildRoot);
    await writeGeneratedShelf(shelf, revisionState);
    await rm(generatedArtifactsRoot, { recursive: true, force: true });
    await rename(stagingRoot, generatedArtifactsRoot);
    published = true;

    for (const staleRoot of staleArtifactRoots) {
      await rm(staleRoot, { recursive: true, force: true });
    }

    return revisionState;
  } finally {
    await rm(stagingRoot, { recursive: true, force: true });
    await rm(artifactStagingRoot, { recursive: true, force: true });
    if (!published) await rm(artifactBuildRoot, { recursive: true, force: true });
  }
}

/** @param {Shelf} shelf @param {ArtifactRevisionState} revisionState */
async function writeGeneratedShelf(shelf, revisionState) {
  const revisions = new Map(
    revisionState.artifacts.map((artifact) => [artifact.route, artifact.revision]),
  );
  const generatedShelf = {
    version: shelf.version,
    shelfRevision: revisionState.shelfRevision,
    artifacts: shelf.artifacts.map(({ project, route, title, description, embedUrl }) => ({
      project,
      route,
      title,
      description,
      revision: revisions.get(route),
      ...(embedUrl ? { embedUrl } : {}),
    })),
  };

  await mkdir(path.dirname(generatedShelfPath), { recursive: true });
  await writeFile(generatedShelfPath, `${JSON.stringify(generatedShelf, null, 2)}\n`);
}

/**
 * Validate the synchronized artifact revisions and ensure Pagefind's content
 * marker remains present without changing source artifacts owned by other projects.
 *
 * @param {Shelf} shelf
 */
export function artifactBuildIntegration(shelf) {
  return {
    name: 'docshelf-artifacts',
    hooks: {
      'astro:build:done': async ({ dir }) => {
        const outputRoot = fileURLToPath(dir);
        const revisionState = JSON.parse(
          await readFile(
            path.join(outputRoot, 'artifacts', artifactRevisionFile),
            'utf8',
          ),
        );
        await assertArtifactSourcesUnchanged(shelf, revisionState);
        const revisions = new Map(
          revisionState.artifacts.map((artifact) => [artifact.route, artifact.revision]),
        );

        for (const artifact of shelf.artifacts) {
          if (artifact.format === 'claude') continue;
          const outputPath = path.join(outputRoot, 'artifacts', ...artifact.route.split('/'));
          const html = await readFile(outputPath, 'utf8');
          if (contentRevision(html) !== revisions.get(artifact.route)) {
            throw new Error(
              `Built artifact does not match its synchronized revision: ${artifact.route}`,
            );
          }

          const searchableHtml = markArtifactForSearch(html, artifact.route);
          if (searchableHtml === html) continue;
          await writeFile(outputPath, searchableHtml);
        }
      },
    },
  };
}

/**
 * Confirm that the published snapshot still matches every registered source.
 *
 * @param {Shelf} shelf
 * @param {ArtifactRevisionState} revisionState
 */
export async function artifactSourcesMatch(shelf, revisionState) {
  const expected = new Map(
    revisionState.artifacts.map((artifact) => [artifact.route, artifact.sourceRevision]),
  );

  for (const artifact of shelf.artifacts) {
    if (artifact.format === 'claude') continue;
    if (!artifact.sourcePath) return false;
    const contents = await readFile(artifact.sourcePath).catch(() => null);
    if (!contents || contentRevision(contents) !== expected.get(artifact.route)) return false;
  }

  return true;
}

/**
 * @param {Shelf} shelf
 * @param {ArtifactRevisionState} revisionState
 */
async function assertArtifactSourcesUnchanged(shelf, revisionState) {
  if (!(await artifactSourcesMatch(shelf, revisionState))) {
    throw new Error(
      'A registered artifact changed during the build; rebuild from a fresh snapshot.',
    );
  }
}

/** @param {string} html @param {string} route */
function markArtifactForSearch(html, route) {
  if (html.includes('data-pagefind-body')) return html;
  if (!/<body(?:\s|>)/i.test(html)) {
    throw new Error(`Cannot mark artifact for search because it has no body: ${route}`);
  }
  return html.replace(/<body(?=\s|>)/i, '<body data-pagefind-body');
}

export function artifactSearchIntegration() {
  return {
    name: 'docshelf-artifact-search',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        const pageCount = await writeSearchIndex(fileURLToPath(dir));
        logger.info(`Built one search index for ${pageCount} HTML files.`);
      },
    },
  };
}

/** @param {string} root */
async function assertSymlinkTree(root) {
  const rootStats = await lstat(root).catch(() => null);
  if (!rootStats) return;
  if (!rootStats.isDirectory() || rootStats.isSymbolicLink()) {
    throw new Error(`${root} must be a generated directory.`);
  }

  const entries = await readdir(root, { withFileTypes: true });
  for (const entry of entries) {
    const entryPath = path.join(root, entry.name);

    if (entry.isDirectory()) {
      await assertSymlinkTree(entryPath);
      continue;
    }

    if (!entry.isSymbolicLink()) {
      throw new Error(
        `Refusing to replace non-symlink content in ${generatedArtifactsRoot}: ${entryPath}`,
      );
    }
  }
}

/** @param {string} activeRoot */
async function findGeneratedArtifactRoots(activeRoot) {
  const entries = await readdir(runtimeRoot, { withFileTypes: true });
  const staleRoots = [];

  for (const entry of entries) {
    const isCurrentOutput = entry.name.startsWith(artifactRootPrefix);
    const isLegacyMarkdownOutput = entry.name.startsWith(legacyMarkdownRootPrefix);
    if (!isCurrentOutput && !isLegacyMarkdownOutput) continue;

    const entryPath = path.join(runtimeRoot, entry.name);
    if (entryPath === activeRoot) continue;
    // Leave roots that another live DocShelf process may still be building from.
    const ownerPid = generatedRootPid(entry.name);
    if (ownerPid !== null && ownerPid !== process.pid && isProcessAlive(ownerPid)) continue;
    if (!entry.isDirectory() || entry.isSymbolicLink()) {
      throw new Error(`Refusing to remove unexpected artifact output: ${entryPath}`);
    }

    const markerName = isCurrentOutput ? artifactOutputMarker : legacyMarkdownOutputMarker;
    const marker = await readFile(path.join(entryPath, markerName), 'utf8').catch(() => null);
    if (marker !== artifactOutputMarkerContents) {
      throw new Error(`Refusing to remove unmarked artifact output: ${entryPath}`);
    }

    staleRoots.push(entryPath);
  }

  return staleRoots;
}

/** Generated roots are named `<prefix><timestamp>-<pid>`. @param {string} name */
function generatedRootPid(name) {
  const match = /-(\d+)$/.exec(name);
  return match ? Number(match[1]) : null;
}

/**
 * @typedef {object} ArtifactRevision
 * @property {string} route
 * @property {string} revision
 * @property {string} sourceRevision
 */

/**
 * @typedef {object} ArtifactRevisionState
 * @property {1} version
 * @property {string} revision
 * @property {string} shelfRevision
 * @property {ArtifactRevision[]} artifacts
 */

/** @param {Shelf} shelf */
async function readArtifactSources(shelf) {
  const snapshots = new Map();

  for (const artifact of shelf.artifacts) {
    if (artifact.format === 'claude') continue;
    if (!artifact.sourcePath) throw new Error(`Missing source path for ${artifact.route}.`);
    const contents = await readFile(artifact.sourcePath);
    snapshots.set(artifact.sourcePath, {
      contents,
      revision: contentRevision(contents),
    });
  }

  return snapshots;
}

/** @param {Shelf} shelf @param {ArtifactRevision[]} artifacts */
function createRevisionState(shelf, artifacts) {
  return {
    version: 1,
    revision: contentRevision(
      JSON.stringify(artifacts.map(({ route, revision }) => ({ route, revision }))),
    ),
    shelfRevision: contentRevision(
      JSON.stringify(
        shelf.artifacts.map(({ project, route, title, description, embedUrl }) => ({
          project,
          route,
          title,
          description,
          ...(embedUrl ? { embedUrl } : {}),
        })),
      ),
    ),
    artifacts,
  };
}

/** @param {unknown} value */
function isRecord(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * @param {Record<string, unknown>} entry
 * @param {string} key
 * @param {number} index
 */
function requiredString(entry, key, index) {
  const value = entry[key];
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`Artifact ${index + 1} requires a non-empty ${key}.`);
  }
  return value;
}

/** @param {string} source @param {number} index */
export function validateSource(source, index) {
  if (path.isAbsolute(source)) {
    throw new Error(`Artifact ${index + 1} source must be relative to DocShelf.`);
  }
  if (!['.html', '.md'].includes(path.extname(source).toLowerCase())) {
    throw new Error(`Artifact ${index + 1} source must be an HTML or Markdown file.`);
  }
}

/**
 * Accept only Claude's public Artifact share and embed URLs. General Claude pages
 * and arbitrary remote HTML are deliberately not valid shelf sources.
 *
 * @param {string} source
 * @returns {{ artifactId: string, publicUrl: string, embedUrl: string } | null}
 */
export function parseClaudeArtifactSource(source) {
  return parseClaudeArtifactUrl(source);
}

/** @param {string} source @returns {'html' | 'markdown'} */
function sourceFormat(source) {
  return path.extname(source).toLowerCase() === '.md' ? 'markdown' : 'html';
}

/** @param {string} route @param {number} index */
export function validateRoute(route, index) {
  if (route.startsWith('/') || route.includes('\\')) {
    throw new Error(`Artifact ${index + 1} route must be relative and use forward slashes.`);
  }

  const segments = route.split('/');
  if (
    segments.some((segment) => !/^[a-z0-9][a-z0-9._-]*$/.test(segment)) ||
    path.posix.normalize(route) !== route ||
    !route.endsWith('.html')
  ) {
    throw new Error(`Artifact ${index + 1} has an invalid route: ${route}`);
  }
}

/** @param {string} root @param {string} candidate */
function isWithin(root, candidate) {
  const relativePath = path.relative(root, candidate);
  return relativePath !== '' && !relativePath.startsWith(`..${path.sep}`) && relativePath !== '..';
}
